// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Auth0WithRedis.Models
{
    public partial class AuthLogin
    {
        public int Id { get; set; }
        public Guid AuthUserId { get; set; }
        public string Os { get; set; }
        public string Ip { get; set; }
        public string Location { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string RefreshToken { get; set; }

        public virtual AuthUsers AuthUser { get; set; }
    }
}